job_uid: product-operations
display_name: Product Operations
display_category: Product
display_cover_image_uri: https://images.ctfassets.net/xri6xnn81z4a/7jdLCa5xoAiTKltPhAuJdu/3f2727214b7b3b644485de91cd3a6ebc/Product-Manager.jpg
display_description_short: Product Operations is a professional who bridges product,
  engineering, and support teams to optimize product delivery and performance.
display_description_long: Product Operations
display_skills_required:
- Product Lifecycle Management (PLM)
available_npcs: []
tasks: []
is_featured: false
